version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./game_data.json:/app/game_data.json
    environment:
      - SECRET_KEY=${SECRET_KEY:-dev-secret}
      - ALGORITHM=HS256

  frontend:
    image: node:18-alpine
    working_dir: /frontend
    command: sh -c "npm install && BACKEND_URL=http://backend:8000 npm run serve -- --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend